### ISSUE TITLE
Missing include files in ROS include dir

### ISSUE THREAD

**Issue by TZ2016** [ethz-asl/mav_comm#34]
Not sure whether this is due to me incorrectly installing the package. 
After `apt-get install ros-indigo-mav-msgs `, in my default ROS include directory, i.e. `/opt/ros/indigo/include/mav_msgs`, at least header files `default_topics.h` and `RollPickYawrateThrust.h` are missing, which are required to compile package `rotors_simulator`. Files `Command*.h` are present.
The version installed is 2.0.3

**Comment by TZ2016** [comment]
I guess it is not intended to have those header files in the ROS include dir. According to rotors_simulator readme, one needs the source of mav_msgs alongside it to compile.

**Comment by helenol** [comment]
We have not released the new packages using the ros release process after
doing a refractor - this should be fixed shortly. For now, checking out
master of mav comm and building them using catkin build will bring you up
to the latest headers.
We will release the new versions of rotors simulator and mav comm as
pre-compiled ros packages soon, and then this will not be an issue.

Sorry for the inconvenience in the meantime!
