### ISSUE TITLE
Missing message in CMakeLists.txt (in tag 3.0.0)

### ISSUE THREAD

**Issue by marianobianchi** [ethz-asl/mav_comm#38]
I don't know if i should create an issue for this but i was having problems compiling PX4 firmware (https://github.com/PX4/Firmware) using ROS command "catkin_make". One of the dependencies was mav_comm/mav_msgs. Using rosinstall_generator, i downloaded mav_comm 3.0.0 version. When i was compiling it, i got an error saying "CommandMotorSpeed.h" was not found.

After checking CMakeLists.txt from mav_msgs i found that CommandMotorSpeed.msg was missing from add_message_files. So, when running catkin_make the files needed to use CommandMotorSpeed message wasn't created and PX4 build fail with the error above.

I added CommandMotorSpeed.msg to CMakeLists.txt and everything worked fine.

**Comment by helenol** [comment]
Ah, so those are unnecessary messages that got fixed (removed) since tag 3.0.0 -- I'll make tag 3.0.1 with the bug fixes (4 latest commits to master). Thanks for the heads up.

**Comment by rikba** [comment]
Assuming to be resolved.
