### ISSUE TITLE
The message mechanism and information flow of the package.

### ISSUE THREAD

**Issue by yajingwang94** [ethz-asl/mav_comm#46]
Hi.

My question is about the topic subscribed and published by plugins loaded by the model.

-1.  I want to know, for example, the` /command/motor_speed` topic and the `/gazebo/command/motor_speed` topic, what is the difference of them?

-2.  If I use a ros node to send control instructions, what is the relations of my rostopics and topics here of the plugins?

I find the `controller_interface plugin` subscribes to the `/command/motor_speed` and publish to the `/gazebo/command/motro_speed`.

 For mav_msgs, will the namespace of the node change the prefix of topic names?

I am trying to integrate the techpod model with px4, but I am a little confused about the transmission mechanism of mav_msgs( I feel that it is a little different from rostopic, although the usage of them are so much likely).

I am trying to figure out the information flow of the package(especially among the plugins loaded by the model).  

I would be really grateful if you can give some help.

**Comment by michaelpantic** [comment]
Closing this very old issue.
