### ISSUE TITLE
change planning_msgs package name

### ISSUE THREAD

**Issue by fmina** [ethz-asl/mav_comm#49]
planning_msgs is an existing open source package https://github.com/code-iai/iai_common_msgs. ROS buildfarm will not allow 2 packages with the same name. We should change `planning_msgs` to something like `mav_planning_msgs`.

Opinions? @helenol @burrimi @ffurrer

**Comment by burrimi** [comment]
are we still using these messages? `mav_planning_msgs` sounds good to me

**Comment by ffurrer** [comment]
yup, agree on `mav_planning_msgs` :), we'll just need to make sure, that we test compatibility with the existing code, that uses these.

**Comment by helenol** [comment]
mav_planning_msgs sounds good.
Should just be the usual stuff in the stack: mav_pathplanning, mav_gui, maybe mav_mbzirc and so on

**Comment by rikba** [comment]
Done https://github.com/ethz-asl/mav_comm/pull/64
