### ISSUE TITLE
Is there a plan to launch this on rosbuild farm for Kinetic and Lunar?

### ISSUE THREAD

**Issue by TSC21** [ethz-asl/mav_comm#51]
Could be interesting to follow up a possible integration in [mavros](https://github.com/mavlink/mavros). Thanks

**Comment by TSC21** [comment]
Hi @rikba! There's a PR to MAVROS that requires a release of `mav_comm` to Lunar (https://github.com/mavlink/mavros/pull/966). Any plans to do the release in the mean time? Thanks

**Comment by rikba** [comment]
Hi @TSC21 

both Lunar and Melodic ros packages will be released soon. See https://github.com/ethz-asl/mav_comm/issues/60

**Comment by TSC21** [comment]
Awesome! Thanks @rikba!
